<?php

define('REVIEWS_IBLOCK_ID', 5);
define('STATUSES_IBLOCK_ID', 7);
define('REVIEW_IBLOCK_AUTHOR_PROP_ID', 9);

define('ALLOWED_AUTHOR_STATUS_CODE', 'publishing');
define('ALLOWED_AUTHOR_STATUS_ID', 35);

define('CONTENT_EDITOR_GROUP_ID', 5);
define('ALLOWED_AUTHOR_GROUP_ID', 6);

define('USER_CLASS_FIELD', 'UF_USER_CLASS');
define('AUTHOR_STATUS_FIELD', 'UF_AUTHOR_STATUS');
